server:
  port: 8080

factservice:
  host: localhost:8081

fibservice:
  host: localhost:8082

opentracing:
  jaeger:
    service-name: ComputeService
    enabled: TRUE
    udp-sender:
      host: localhost

